$(document).ready(function(){
  $(".toggle1").click(function(){
    $(".image1").toggle();
    $(".design").toggle();
  });
  $(".toggle2").click(function(){
    $(".image2").toggle();
    $(".development").toggle();
  });
  $(".toggle3").click(function(){
    $(".image3").toggle();
    $(".product_mgmt").toggle();
  });
});